apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetimer-async
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubetimer
  template:
    metadata:
      labels:
        app: kubetimer
    spec:
      serviceAccountName: kubetimer-sa
      containers:
      - name: operator
        image: ryanjorgeac/timer-async:v0.0.2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "500m"